// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtiiveodxiaknwrtlvhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0aWl2ZW9keGlha253cnRsdmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjAyNDUsImV4cCI6MjA2NDY5NjI0NX0.Og-oOJ0eYCs8eT-AjZ5Mh_0TSjL_wM72EpwHxwcBWns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);